USE COACHX_LEARNING

CREATE TABLE BOOKS_DETAILS
(
BOOK_ID INT,
TITLE VARCHAR(50),
LANG VARCHAR(30),
NUM_PAGES INT,
PUBLISHER_ID VARCHAR(60),
PUBLICATION_DATE VARCHAR(70)
)

DROP TABLE BOOK
DROP TABLE BOOKS
DROP TABLE BOOKS_DETAIL

CREATE TABLE CUSTOMER
(
CUST_ID INT,
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(60),
EMAIL VARCHAR(50)
)

SELECT * FROM BOOKS_DETAILS-------------------------------------------TABLE 1
SELECT * FROM CUSTOMER------------------------------------------------TABLE2

ALTER TABLE CUSTOMER
ADD BOOK_PURCHASED VARCHAR(60)


SELECT TOP 1 BOOK_PURCHASED
FROM CUSTOMER-----------------------------------------------------------TO FIND THE HIGHEST SELLING BOOK

SELECT DISTINCT COUNT(TITLE) AS TOTAL_BOOKS FROM BOOKS_DETAILS-----------TO FIND THE COUNT OF BOOKS

SELECT * FROM BOOKS_DETAILS----------------------------------------------TO FIND THE ENGLISH LANGUAGE BOOKS
WHERE LANG = 'ENGLISH'


SELECT * FROM BOOKS_DETAILS----------------------------------------------TO FIND THE HINDI LANGUAGE BOOKS
WHERE LANG = 'HINDI'

SELECT * FROM BOOKS_DETAILS----------------------------------------------TO FIND THE URDU LANGUAGE BOOKS
WHERE LANG = 'URDU'

SELECT * FROM BOOKS_DETAILS
WHERE BOOK_ID = 4

SELECT * FROM BOOKS_DETAILS
WHERE NUM_PAGES > 400

SELECT TOP 3 NUM_PAGES, TITLE--------------------------------------------TO FIND BOOKS WITH HIGHEST NUMBER OF PAGES
FROM BOOKS_DETAILS
ORDER BY NUM_PAGES DESC

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS CUST_NAME FROM CUSTOMER------JOINING FIRST AND LAST NAME FROM CUSTOMER TABLE

SELECT * FROM CUSTOMER----------------------------------------------------TO FIND DETAILS OF CUSTOMER FROM CUST_TABLE
WHERE CUST_ID = 4

SELECT * FROM BOOKS_DETAILS AS B-----------------------------------------PERFORMING INNER JOIN ON BOTH TABLES BASED ON COMMON ID
INNER JOIN CUSTOMER AS C
ON B.BOOK_ID = C.CUST_ID

SELECT * FROM BOOKS_DETAILS AS B-----------------------------------------PERFORMING LEFT JOIN ON BOTH TABLES BASED ON COMMON ID
LEFT JOIN CUSTOMER AS C
ON B.BOOK_ID = C.CUST_ID

SELECT * FROM BOOKS_DETAILS AS B-----------------------------------------PERFORMING RIGHT JOIN ON BOTH TABLES BASED ON COMMON ID
RIGHT JOIN CUSTOMER AS C
ON B.BOOK_ID = C.CUST_ID

SELECT * FROM BOOKS_DETAILS AS B-----------------------------------------PERFORMING OUTER JOIN ON BOTH TABLES BASED ON COMMON ID
FULL OUTER JOIN CUSTOMER AS C
ON B.BOOK_ID = C.CUST_ID

SELECT * FROM BOOKS_DETAILS --------------------------------------------PERFORMING CROSS JOIN ON BOTH TABLES
CROSS JOIN CUSTOMER 

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME, ' - ', EMAIL) AS CUST_DETAILS FROM CUSTOMER











